# Generated by Django 5.2.1 on 2025-07-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_squashed_0002_add_and_delete_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='state',
            field=models.CharField(choices=[('BR', 'BORRADOR'), ('PU', 'PUBLICADO'), ('PR', 'PRIVADO')], default='BR', max_length=2),
        ),
    ]
