# Generated by Django 5.2.1 on 2025-07-11 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_productmodel_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='state',
        ),
    ]
