# Generated by Django 5.2.1 on 2025-07-11 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_remove_productmodel_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ['-updated', '-timestamp']},
        ),
        migrations.AddField(
            model_name='productmodel',
            name='publish_timestap',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='state',
            field=models.CharField(choices=[('PU', 'PUBLICADO'), ('DF', 'BORRADOR'), ('PR', 'PRIVADO')], default='DF', max_length=2),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
